version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: activitytracking-db
    environment:
      POSTGRES_DB: activitytracking_db
      POSTGRES_USER: activitytracking_user
      POSTGRES_PASSWORD: activitytracking_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: