spring.datasource.url=jdbc:postgresql://localhost:5432/activity_tracking
spring.datasource.username=postgres
spring.datasource.password=131955yehia
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format-sql=true
server.error.include-message=always