spring.application.name=activitytracking

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/activitytracking_db
spring.datasource.username=activitytracking_user
spring.datasource.password=activitytracking_pass

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration